t9917: work around a flake
I did not get this on my old machine (WSL, running on a Surface Book 2),
but when I run t9917 on my new machine (also WSL, running on a fast
ThinkPad with a Ryzen CPU), it fails consistently.

The symptom is:

	[...]
	 create mode 100644 5/expect
	 create mode 100644 5/new
	++ git blame-tree --max-depth=1 -- 5
	8e51acd91c61d387e93bb16e47693ae8291ba74b        5/expect
	8e51acd91c61d387e93bb16e47693ae8291ba74b        5/new
	8e51acd91c61d387e93bb16e47693ae8291ba74b        5/actual
	+++ ls -t
	.git/objects/info/blame-tree/1ee9183b1f737da4d348ea42281bd1dd682c5d52.btc
	.git/objects/info/blame-tree/313c6b9e42fd29af2e09cf6e976c39a30f19d3ed.btc
	.git/objects/info/blame-tree/3c28d037e32cd30eefd8183a83153083cced6cb7.btc
	.git/objects/info/blame-tree/a396f217640ac5e25cbc6ead90be2e223520f828.btc
	.git/objects/info/blame-tree/a43fcc847c229375b0a430270e62a3f2d8a77d97.btc
	.git/objects/info/blame-tree/ac94b1b9ad973ac9d43ebe6a83140815c19c63a0.btc
	+++ head -n 1
	++
	file=.git/objects/info/blame-tree/a396f217640ac5e25cbc6ead90be2e223520f828.btc
	++ backtime=5
	++ test-tool chmtime =-5
	.git/objects/info/blame-tree/a396f217640ac5e25cbc6ead90be2e223520f828.btc
	++ ls -t .git/objects/info/blame-tree/
	++ tail -n 3 before-all
	++ head -n 3 before-all
	++ git -c blameTree.maxWrites=2 blame-tree --update-cache HEAD
	++ ls -t .git/objects/info/blame-tree/
	++ tail -n 3 after-all
	++ head -n 3 after-all
	++ test_cmp before-oldest after-newest
	++ test 2 -ne 2
	++ eval 'diff -u' '"$@"'
	+++ diff -u before-oldest after-newest
	--- before-oldest       2022-07-15 13:26:39.114275985 +0000
	+++ after-newest        2022-07-15 13:26:39.124275985 +0000
	@@ -1,3 +1,3 @@
	 3c28d037e32cd30eefd8183a83153083cced6cb7.btc
	-a43fcc847c229375b0a430270e62a3f2d8a77d97.btc
	 1ee9183b1f737da4d348ea42281bd1dd682c5d52.btc
	+a43fcc847c229375b0a430270e62a3f2d8a77d97.btc
	error: last command exited with $?=1
	not ok 26 - modify multiple caches, with limit